language: cpp
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages:
          - g++-9
    env:
      - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
  - os: osx
    osx_image: xcode8
compiler:
  - gcc
before_install:
  - eval "${MATRIX_EVAL}"
script:
  - cmake . && cmake --build . --config Release
  - ./md5list fixtures
  - cat *.csv
  - md5sum fixtures/*