language: cpp
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages:
          - g++-8
    env:
      - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
  - os: osx
    osx_image: xcode8
compiler:
  - gcc
before_install:
  - eval "${MATRIX_EVAIL}"
script: cmake . && cmake --build . --config Release
